/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData chat = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData users = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData left = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData direction = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData cancel = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData ok = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData plus = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData paper_plane = const IconData(0xf1d8, fontFamily: _kFontFam);
}
