name: haleo_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_advanced_networkimage: 0.5.0
  intl_translation: 0.17.3
  cupertino_icons: 0.1.2
  firebase_core: 0.4.2+1
  firebase_auth: 0.15.1
  cloud_firestore: 0.12.11
  firebase_messaging: 5.1.8
  geoflutterfire: 2.0.3+5
  google_sign_in: 4.0.14
  darter_base: ^0.0.2
  vibration: 1.2.2
  share: 0.6.3+4
  rxdart: 0.22.6
  intl: 0.15.8
  angles: 1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/icon.png"
  image_path_ios: "assets/images/icon_ios.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
  - family:  CustomIcons
    fonts:
    - asset: assets/fonts/CustomIcons.ttf

  assets:
    - assets/fonts/
    - assets/images/